version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - LATITUDE=52.4064
      - LONGITUDE=16.9252
